### ISSUE TITLE
CLI: `query` declaration ignored

### ISSUE THREAD

**Issue by travtarr** [usebruno/bruno#1681]
BrunoCLI v1.9.2

I've been trying to use the CLI and manually modifying the requests via their .bru files without using the app at all.

I've found that the following doesn't work:
```
get {
  url: https://api.textlocal.in/send
}

query {
  apiKey: secret
  numbers: 9988776655
  message: hello
}
```
(notice that the `url` does not contain the query parameters as shown in the docs)

The following does work (copy-paste from [docs](https://docs.usebruno.com/bru-language-tag-reference.html#query))
```
get {
  url: https://api.textlocal.in/send?apiKey=secret&numbers=9988776655&message=hello
}

query {
  apiKey: secret
  numbers: 9988776655
  message: hello
}
```

It seems counter-intuitive to have to duplicate the query parameters onto the url, and also causes some debugging issues if they are not synchronized.

**Comment by ebrannin-bw** [comment]
Possibly related (v3.1.4):

**it seems like Bruno ignores Query params unless (on disk) they're duplicated in the `url`**

1. I imported an OpenAPI schema in the UI
2. The import (in YAML format) generated a bunch of parameters, with a mix of enabled/disabled (see below)
3. (Outside Bruno) I staged the Bruno collection in git to track changes
4. I sent a request, and got an API response.
5. I tweaked one quary-parameter's value in the Bruno UI
6. I sent a request, and got a _very different_ API response.
7. I reverted my tweak from step 5
8. I sent another request, and got the same response as step 6.
9. (Outside Bruno) I looked at the git diff, and the `path` had suddenly gone from path-only to path+query (see below)


Example parameters generated:

```yaml
  params:
    - name: callback
      value: ""
      type: query
      description: URL to which we'll make the callback request
      disabled: true
    - name: callback_method
      value: POST
      type: query
      description: HTTP method by which the callback request will be made
```

The git diff after I tweaked a param in the UI:

```diff
-  url: "{{baseUrl}}/v1/thing"
+  url: "{{baseUrl}}/v1/thing?callback_method=POST&(many more params)
```
