### ISSUE TITLE
support OpenAPI links

### ISSUE THREAD

**Issue by mockersf** [usebruno/bruno#2623]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

OpenAPI supports defining links between different routes: a value extracted from the response of a route can be used as a parameter of another route

https://swagger.io/docs/specification/links/

When importing a collection containing links, replace the link definition by a script extracting the value to a variable, and replace the link usage by this variable

example link definition:
```yaml
links:
  GetUserByUserId:
    operationId: getUser
    parameters:
      userId: '$response.body#/id'
```

### Mockups or Images of the feature

link extraction:
<img width="1280" alt="link extraction" src="https://github.com/usebruno/bruno/assets/8672791/c952e449-f464-4684-8967-69045bb39b46">

link usage:
<img width="1280" alt="link usage" src="https://github.com/usebruno/bruno/assets/8672791/0e98d180-c3ae-4419-8171-e7c12ba6d8eb">
